<style>
table#tb_event_addform td:nth-child(2) select:nth-child(1){
    border:1px #abc solid;
    width:250px;
    float: left;
}
div.btn_area{
    width:250px;
}
textarea {
    resize: vertical;
}
.ui-datepicker {font-size: 12px !important;}
</style>
<script>
$(function(){
    $('#address').on('keypress', function(e){
        if(e.keyCode == 13 && $('#address').val() && $.trim($('#address').val()) != ''){
            showGMap();
            return false;
        }
    });
    $('#geocoding').button({icons:{primary:'ui-icon-script'}});
    $('#geocoding').click(function(e){
        e.preventDefault();
        if($.trim($('#address').val())){
            showGMap();
        }else{
            $('#address').focus();
            showCommonAlertDialog('注意','場所を入力して下さい。');
            return;
        }
    });
    $('#event_add').button({icons:{primary:'ui-icon-pencil'}});
    $('#event_add').click(function(){
        if($('select#class').val() == ''){
            $('select#class').focus();
            showCommonAlertDialog('注意','クラスを選択して下さい。');
            return;
        }
        if($.trim($('#event_title').val()) == ''){
            $('#event_title').val('');
            $('#event_title').focus();
            showCommonAlertDialog('注意','行事のタイトルを入力して下さい。');
            return;
        }
        if($.trim($('#event_contents').val()) == ''){
            $('#event_contents').val('');
            $('#event_contents').focus();
            showCommonAlertDialog('注意','行事の内容を入力して下さい。');
            return;
        }
        $("#yes_no_common_alert").html('行事を作成しますか？');
        var date = $.trim($('#event_date').val());
        if(date){
            if(date.length != 8){
                showCommonAlertDialog('エラー','日付を確認して下さい。');
                return;
            }
        }
        $("#yes_no_common_alert").dialog({
            title:'確認',
            modal: true,
            draggable: false,
            closeOnEscape: false,
            resizable: false,
            height: 'auto',
            minHeight: 0,
            width: 'auto',
            open: function(event, ui) {
                setDialogDesign($(this));
                $('.ui-dialog-buttonpane').find('button:contains("はい")').button({icons: {primary: 'ui-icon-circle-triangle-e'}});
                $('.ui-dialog-buttonpane').find('button:contains("キャンセル")').button({icons: {primary: 'ui-icon-circle-close'}});
            },
            buttons: {
                "はい": function() {
                    $(this).dialog("close");
                    $.ajax({
                        url: '/event/postcontents',
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            class_id:$('select#class').val(),
                            title:$.trim($('#event_title').val()),
                            contents:$.trim($('#event_contents').val()),
                            address:$('#address').val(),
                            date:date
                        },
                        beforeSend: function(xhr){
                            xhr.setRequestHeader("If-Modified-Since", "Thu, 01 Jun 1970 00:00:00 GMT");
                        },
                        error: function(xhr, status, e){
                            console.log(xhr);
                            console.log(status);
                            console.log(e);
                            showCommonAlertDialog('エラー','システムエラーが発生しました。しばらくしてからやり直して下さい。');
                        },
                        success: function(d){
                            console.log(d);
                            if(d.status == _SEAR_){
                                showCommonAlertDialog('エラー','セッション終了です。再びログインして下さい。','/login');
                            }else{
                                if(d.status == '0'){
                                    $('#event_add_cancel').trigger('click');
                                }else{
                                    showCommonAlertDialog('エラー',d.message);
                                }
                            }
                        },
                        complete: function(){}
                    });
                },
                "キャンセル": function() {
                    $(this).dialog("close");
                }
            }
        });
    });
    $('#event_add_cancel').button({icons:{primary:'ui-icon-arrowreturnthick-1-w'}});
    $('#event_add_cancel').click(function(){
        var params = {
            url:'/event/list',
            pageno:$('#pageno').val(),
            trigger:$('#trigger').val(),
            backbutton_target:true,
            history_seq:getNewHistorySeq()
        };
        window.History.pushState(params, null, '/');
    });
    $("#event_date").datepicker({
        minDate: 0,
        defaultDate: new Date(),
        beforeShow: function() {
        }
    });
    $('#map').hide();
});
function showGMap(){
    GMaps.geocode({
        address: $('#address').val().trim(),
        callback: function(results, status){
            if(status == 'OK'){
                var latlng = results[0].geometry.location;
                $('#map').slideDown('fast', function(){
                    var map = new GMaps({
                        el: '#map',
                        lat: latlng.lat(),
                        lng: latlng.lng()
                    });
                    map.setCenter(latlng.lat(), latlng.lng());
                    map.addMarker({
                        lat: latlng.lat(),
                        lng: latlng.lng()
                    });
                });
            }else{
                showInfoMessage(300,'地図上では確認できませんでした。',2000,'slow');
                if($('#map').is(':visible')){
                    $('#map').slideUp();
                }
            }
        }
    });
}
</script>
<h2>行事<span>行事内容を作成します。</span></h2>
<table style='width:940px' id='tb_event_addform'>
<?php
    $classCnt = count($this->classlist);
    $i = 1;
    if($classCnt > 0){
?>
    <tr>
        <td width='170px' style='background-color:#f7fed8'><font color='red'>*</font>クラス</td>
        <td>
            <select id='class' style='margin:0px;'>
            <option value=''>クラスを選択して下さい。</option>
<?php 
        if($this->loginedInfo['member_type'] == '1'){
?>
            <option value='00'>全組</option>
<?php 
        }
            foreach($this->classlist as $class){
?>
            <option value='<?php echo $class['id'];?>'><?php echo $class['name'];?>(<?php echo $class['approved_cnt'];?>)</option>
<?php
        }
?>
            </select>
        </td>
    </tr>
<?php
    }
?>
    <tr>
        <td width='170px' style='background-color:#f7fed8'><font color='red'>*</font>タイトル</td>
        <td style='text-align:left'><input type='text' name="event_title" id="event_title" style='margin:0px;width:400px;border-radius:0px;border:1px #abc solid' /></td>
    </tr>
    <tr>
        <td style='width=170px;background-color:#f7fed8'><font color='red'>*</font>内容</td>
        <td ><textarea name="event_contents" id="event_contents" cols="120" rows="6" wrap="hand" style='width:750px;border:1px #abc solid'></textarea></td>
    </tr>
    <tr>
        <td style='width=170px;background-color:#f7fed8'>場所</td>
        <td style='text-align:left;height:30px;vertical-align:middle;' width='400px'>
            <input type='text' id='address' style='width:400px;margin-left:0px;border-radius:0px;border:1px #abc solid;float:left'/>
            <button id='geocoding' style='margin-left:5px;'>地図で確認</button>
            <div id="map" style="width:752px;height:400px;margin-top:5px;clear:both"></div>
        </td>
    </tr>
    <tr>
        <td style='width=170px;background-color:#f7fed8'>日付</td>
        <td style='text-align:left'><input type='text' id='event_date' style='margin:0px;border-radius:0px;border:1px #abc solid'/></td>
    </tr>
</table>
<div class="btn_area">
    <button id='event_add'>作成</button>
    <button id='event_add_cancel'>キャンセル</button>
</div>