<style>
table#tb_mamatalk tr.clickable_yes {
    cursor:pointer;
}
table#tb_title td:nth-child(1) select:nth-child(1){
    border:1px #000 solid;
    width:80px;
}
table#tb_title td:nth-child(1) select:nth-child(2){
    border:1px #000 solid;
    width:70px;
}

table#tb_mamatalk tr.clickable_yes td:nth-child(2){
    text-align:left;
}
table#tb_mamatalk tr.clickable_yes td:nth-child(3){
    text-align:left;
}
table#tb_mamatalk tr.clickable_yes td:nth-child(4){
    text-align:left;
}
table#tb_mamatalk tr.clickable_no td:nth-child(2){
    text-align:left;
}
table#tb_mamatalk tr.clickable_no td:nth-child(3){
    text-align:left;
}
table#tb_mamatalk tr.clickable_no td:nth-child(4){
    text-align:left;
}
</style>
<script>
$(function(){
    $("table#tb_mamatalk tr.clickable_yes").mouseover(function(){
        $(this).removeClass('already_read_mouseout');
        $(this).addClass('already_read_mouseover');
    });
    $("table#tb_mamatalk tr.clickable_yes").mouseout(function(){
        $(this).removeClass('already_read_mouseover');
        $(this).addClass('already_read_mouseout');
    });
    $("table#tb_mamatalk tr.clickable_yes").on('click', function(){
        var params = {
            url:'/mamatalk/detail',
            mamatalk_id:$(this).children().children('input[type="hidden"][name="mamatalk_id"]').val(),
            reply_pageno:1,
            reply_cnt:$(this).children().children('input[type="hidden"][name="reply_cnt"]').val(),
            backbutton_target:true,
            history_seq:getNewHistorySeq()
        };
        window.History.pushState(params, null, '/');
    });
    $('#mamatalk_search').button({icons:{primary:'ui-icon-search'}});
    $('#mamatalk_search').click(function(){
        getListByPageno(1);
    });
    $('#mamatalk_add_form').button({icons:{primary:'ui-icon-circle-plus'}});
    $('#mamatalk_add_form').click(function(){
        var params = {
            url:'/mamatalk/addform',
            action:'mamatalk',
            class_id:$('#class_id').val(),
            backbutton_target:true,
            history_seq:getNewHistorySeq()
        };
        window.History.pushState(params, null, '/');
    });
    $('#trigger').val('pageno');
    $('#pageno').val('<?php echo $this->pageno;?>');
});
function goFirstPage(){
    $('#pageno').val(1);
    getmamatalkList();
}
function getListByPageno(pageno){
    $('#pageno').val(pageno);
    getmamatalkList();
}
function goNextPageGroup(){
    $('#trigger').val('nextgroup');
    getmamatalkList();
}
function goPrevPageGroup(){
    $('#trigger').val('prevgroup');
    getmamatalkList();
}
function goLastPage(){
    $('#trigger').val('lastpageno');
    getmamatalkList();
}
function getmamatalkList(){
    var params = {
        url:'/mamatalk/list',
        class_id:$('#class_id').val(),
        pageno:$('#pageno').val(),
        trigger:$('#trigger').val(),
        backbutton_target:true,
        history_seq:getNewHistorySeq()
    };
    window.History.pushState(params, null, '/');
}
</script>
<h2>ママトーク<span></span></h2>
<table id='tb_title'>
    <tr>
        <td width='150px'>
            <select id='class_id' style='width:150px;'>
                <option value='00'>全体の組</option>
            <?php
                foreach($this->classlist as $cls){
                    $selected = '';
                    if($cls['id'] == $this->class_id){
                        $selected = 'selected';
                    }
            ?>
                <option value='<?php echo $cls["id"];?>' <?php echo $selected;?>><?php echo $cls['name'];?></option>
            <?php
                }
            ?>
            </select>
        </td>
        <td style='text-align:left'>
            <button id='mamatalk_search'>検索</button>
            <button id='mamatalk_add_form'>作成</button>
        </td>
    </tr>
</table>
<table id="tb_mamatalk">
<?php
if(count($this->list) > 0 ){
    foreach ($this->list as $data) {
        $have_picture_data = '';
        if(isset($data['have_pictures_url']) && $data['have_pictures_url'] != ''){
            $have_picture_data = "<img src='".$data['have_pictures_url']."' style='vertical-align: middle;'/>";
        }
        $data['contents'] = '<font style="font-weight:bold;">'.$data['title'].'</font><br>'.$data['contents'];
?>
    <tr class='clickable_yes'>
        <td width='75px'><?php echo $data['class_name'];?>
            <input type='hidden' name='mamatalk_id' value='<?php echo $data['mamatalk_id']?>'/>            
            <input type='hidden' name='reply_cnt' value='<?php echo $data['reply_cnt']?>'/>
        </td>
        <td width='135px'><?php echo $data['writer_name'];?><br><?php echo $data['createtime'];?></td>
        <td width='20px'><?php echo $have_picture_data;?></td>
        <td><?php echo $data['contents'];?></td>
        <td width='35px'>
            <?php if ($data['good_cnt'] > 0){?><div class='valign_middle' style='margin-right:2px'><img src='/img/icon/heart.png'/></div><?php echo $data['good_cnt'];?><?php }?>
            <?php if ($data['reply_cnt'] > 0){?><div class='valign_middle' style='margin-right:2px'><img src='/img/icon/balloon.png'/></div><?php echo $data['reply_cnt'];?><?php }?>
        </td>
    </tr>
<?php 
    }
?>
    <tr class="page_control">
        <td colspan="6">
<?php 
    if($this->pagenator['firstPageFlag'] == 0){
?>
            <p>最初</p>
<?php 
    }else{
?>
            <a href='javascript:goFirstPage();'>最初</a>
<?php 
    }
    if($this->pagenator['preGroupFlag'] == 0){
?>
            <p>前へ</p>
<?php
    }else{
?>
            <a href='javascript:goPrevPageGroup();'>前へ</a>
<?php
    }
    foreach($this->pagenator['pagenoArr'] as $pno){
        if($pno == $this->pageno){
?>
                <p id="here"><?php echo $pno;?></p> 
<?php 
        }else{
?>
                <a href="javascript:getListByPageno(<?php echo $pno;?>)"><?php echo $pno;?></a> 
<?php
        }
    }
    if($this->pagenator['nextGroupFlag'] == 0){
?>
            <p>次へ</p>
<?php 
    }else{
?>
            <a href='javascript:goNextPageGroup();'>次へ</a>
<?php 
    }
    if($this->pagenator['lastPageFlag'] == 0){
?>
            <p>最後</p>
<?php 
    }else{
?>
            <a href='javascript:goLastPage();'>最後</a>
<?php 
    }
?>
        </td>
    </tr>
<?php
}
?>    
</table>