<style>
.table_picture{
    background-color:#ffffff;
}
.td_picture {
    width:60px;
    border-bottom: none;
}
.typeDiv{
    background-color:#FFC0CB;
    color:#800080;
    border-radius:4px;
}
.td_data {
    border-bottom: none;
}
.table_data td {
    padding: 7px 5px !important;
}
</style>
<script>
$(function(){
    $('.table_picture td').css({'border-bottom':'none'});
    $('.table_data td').css({'border-bottom':'none'});
    $('.btn_approve').button({icons:{primary:'ui-icon-circle-check'}});
    $('.btn_approve').click(function(){
        var member_id = $(this).siblings('input[type=hidden][name=member_id]').val();
        var member_type = $(this).siblings('input[type=hidden][name=member_type]').val();
        var kids_id = $(this).siblings('input[type=hidden][name=kids_id]').val();
        $("#yes_no_common_alert").html('承認しますか');
        $("#yes_no_common_alert").dialog({
            title:'確認',
            modal: true,
            draggable: false,
            closeOnEscape: false,
            resizable: false,
            height: 'auto',
            minHeight: 0,
            width: 'auto',
            open: function(event, ui) {
                setDialogDesign($(this));
                $('.ui-dialog-buttonpane').find('button:contains("はい")').button({icons: {primary: 'ui-icon-circle-triangle-e'}});
                $('.ui-dialog-buttonpane').find('button:contains("キャンセル")').button({icons: {primary: 'ui-icon-circle-close'}});
            },
            buttons: {
                "はい": function() {
                    $(this).dialog("close");
                    $.ajax({
                        url: '/mng/approve',
                        type: 'GET',
                        dataType: 'json',
                        data: {
                            member_id:member_id,
                            member_type:member_type,
                            kids_id:kids_id
                        },
                        beforeSend: function(xhr){
                            xhr.setRequestHeader("If-Modified-Since", "Thu, 01 Jun 1970 00:00:00 GMT");
                        },
                        error: function(xhr, status, e){
                            console.log(xhr);
                            console.log(status);
                            console.log(e);
                            showCommonAlertDialog('エラー','システムエラーが発生しました。しばらくしてからやり直して下さい。');
                        },
                        success: function(d){
                            console.log(d);
                            if(d.status == _SEAR_){
                                showCommonAlertDialog('エラー','セッション終了です。再びログインして下さい。','/login');
                            }else{
                                if(d.status == '0'){
                                    getList();
                                    if(d.push_send_cnt && d.push_send_cnt > 0){
                                        showInfoMessage(300,'プッシュ通知を正常的に送りました。',2000,'slow');
                                    }
                                }else{
                                    showCommonAlertDialog('エラー',d.message);
                                }
                            }
                        },
                        complete: function(){}
                    });
                },
                "キャンセル": function() {
                    $(this).dialog("close");
                }
            }
        });
    });
    $('.btn_reject').click(function(){
        var member_id = $(this).siblings('input[type=hidden][name=member_id]').val();
        var member_type = $(this).siblings('input[type=hidden][name=member_type]').val();
        var kids_id = $(this).siblings('input[type=hidden][name=kids_id]').val();
        $("#yes_no_common_alert").html('拒否しますか');
        $("#yes_no_common_alert").dialog({
            title:'確認',
            modal: true,
            draggable: false,
            closeOnEscape: false,
            resizable: false,
            height: 'auto',
            minHeight: 0,
            width: 'auto',
            open: function(event, ui) {
                setDialogDesign($(this));
                $('.ui-dialog-buttonpane').find('button:contains("はい")').button({icons: {primary: 'ui-icon-circle-triangle-e'}});
                $('.ui-dialog-buttonpane').find('button:contains("キャンセル")').button({icons: {primary: 'ui-icon-circle-close'}});
            },
            buttons: {
                "はい": function() {
                    $(this).dialog("close");
                    $.ajax({
                        url: '/mng/reject',
                        type: 'GET',
                        dataType: 'json',
                        data: {
                            member_id:member_id,
                            member_type:member_type,
                            kids_id:kids_id
                        },
                        beforeSend: function(xhr){
                            xhr.setRequestHeader("If-Modified-Since", "Thu, 01 Jun 1970 00:00:00 GMT");
                        },
                        error: function(xhr, status, e){
                            console.log(xhr);
                            console.log(status);
                            console.log(e);
                            showCommonAlertDialog('エラー','システムエラーが発生しました。しばらくしてからやり直して下さい。');
                        },
                        success: function(d){
                            console.log(d);
                            if(d.status == _SEAR_){
                                showCommonAlertDialog('エラー','セッション終了です。再びログインして下さい。','/login');
                            }else{
                                if(d.status == '0'){
                                    getList();
                                    if(d.push_send_cnt && d.push_send_cnt > 0){
                                        showInfoMessage(300,'プッシュ通知を正常的に送りました。',2000,'slow');
                                    }
                                }else{
                                    showCommonAlertDialog('エラー',d.message);
                                }
                            }
                        },
                        complete: function(){                            
                        }
                    });
                },
                "キャンセル": function() {
                    $(this).dialog("close");
                }
            }
        });
    });
    $('.btn_reject').button({icons:{primary:'ui-icon-circle-close'}});
    $('#trigger').val('pageno');
    $('#pageno').val('<?php echo $this->pageno;?>');
});
function goFirstPage(){
    $('#pageno').val(1);
    getList();
}
function getListByPageno(pageno){
    $('#pageno').val(pageno);
    getList();
}
function goNextPageGroup(){
    $('#trigger').val('nextgroup');
    getList();
}
function goPrevPageGroup(){
    $('#trigger').val('prevgroup');
    getList();
}
function goLastPage(){
    $('#trigger').val('lastpageno');
    getList();
}
function getList(){
    var params = {
        url:'/mng/approvallist',
        pageno:$('#pageno').val(),
        trigger:$('#trigger').val(),
        backbutton_target:true,
        history_seq:getNewHistorySeq(),
        leftmenu:'approval'
    };
    window.History.pushState(params, null, '/');
}
</script>
<h2>未承認リスト<span></span></h2>
<table>
<?php
if(count($this->list) > 0 ){
    foreach ($this->list as $data) {
        $typeStr = ($data['member_type'] == '3') ? '子供会員' : '先生';
?>
    <tr>
        <td class='td_picture'>
            <table class='table_picture'>
                <tr>
                    <td>
                        <div class='typeDiv'><?php echo $typeStr?></div>
                    </td>
                </tr>
                <tr>
                    <td width='65px'>
                        <p style='position:relative'>
                            <img src='<?php echo $data['img']; ?>' style='width:60px;height:67px;'/>
                            <?php if($data['member_type'] == '3'){?><img src='<?php echo $data['kids_sex_img']; ?>' style='position:absolute;top:42px;left:35px;'/><?php }?>
                        </p>
                    </td>
                </tr>
            </table>
        </td>
        <td class='td_data'>
            <table class='table_data'>
<?php if($data['member_type'] == '3'){?>
                <tr>
                    <td style='background-color:#f7fed8' width='125px'>名前</td>
                    <td style='text-align:left'><?php echo $data['kids_name'];?></td>
                </tr>
                <tr>
                    <td style='background-color:#f7fed8'>保護者</td>
                    <td style='text-align:left'><?php echo $data['member_name'];?></td>
                </tr>
                <tr>
                    <td style='background-color:#f7fed8'>誕生日</td>
                    <td style='text-align:left'><?php echo $data['birthday_str'];?></td>
                </tr>
<?php }else{?>
                <tr>
                    <td style='background-color:#f7fed8' width='125px'>名前</td>
                    <td style='text-align:left'><?php echo $data['member_name'];?></td>
                </tr>
                <tr>
                    <td style='background-color:#f7fed8'>メール</td>
                    <td style='text-align:left'><?php echo $data['email'];?></td>
                </tr>
                <tr>
                    <td style='background-color:#f7fed8'>電話番号</td>
                    <td style='text-align:left'><?php echo $data['phonenum'];?></td>
                </tr>         
<?php }?>
            </table>
        </td>
        <td class='td_data'>
            <table class='table_data'>
                <tr>
                    <td style='background-color:#f7fed8' width='125px'>クラス</td>
                    <td style='text-align:left'><?php echo $data['class_name'];?></td>
                </tr>
                <tr>
                    <td style='background-color:#f7fed8'>申請時間</td>
                    <td style='text-align:left'><?php echo $data['createtime'];?></td>
                </tr>
                <tr>
                    <td style='background-color:#f7fed8'>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
        <td width='200px'>
            <button class='btn_approve'>承認</button>
            <button class='btn_reject'>拒否</button>
            <input type='hidden' name='member_id' value='<?php echo $data["member_id"]?>'/>
            <input type='hidden' name='member_type' value='<?php echo $data["member_type"]?>'/>
            <input type='hidden' name='kids_id' value='<?php echo $data["kids_id"]?>'/>
        </td>
    </tr>
<?php 
    }
?>
    <tr class="page_control">
        <td colspan="6">
<?php 
    if($this->pagenator['firstPageFlag'] == 0){
?>
            <p>最初</p>
<?php 
    }else{
?>
            <a href='javascript:goFirstPage();'>最初</a>
<?php 
    }
    if($this->pagenator['preGroupFlag'] == 0){
?>
            <p>前へ</p>
<?php
    }else{
?>
            <a href='javascript:goPrevPageGroup();'>前へ</a>
<?php
    }
    foreach($this->pagenator['pagenoArr'] as $pno){
        if($pno == $this->pageno){
?>
                <p id="here"><?php echo $pno;?></p> 
<?php 
        }else{
?>
                <a href="javascript:getListByPageno(<?php echo $pno;?>)"><?php echo $pno;?></a> 
<?php
        }
    }
    if($this->pagenator['nextGroupFlag'] == 0){
?>
            <p>次へ</p>
<?php 
    }else{
?>
            <a href='javascript:goNextPageGroup();'>次へ</a>
<?php 
    }
    if($this->pagenator['lastPageFlag'] == 0){
?>
            <p>最後</p>
<?php 
    }else{
?>
            <a href='javascript:goLastPage();'>最後</a>
<?php 
    }
?>
        </td>
    </tr>
<?php
}
?>    
</table>