<style>
.kids_table{
    background-color:#e0ecfe;
}
.kids_td {
    width:100% !important;
    border: none !important;
    height: 200px;
}
div.outer {  
    display: table;
    height: 80px;
    width: 300px;
    background: #E3F2DA;  
    color: #5C5C5C;
    border-radius:10px;
    margin:15px auto 5px;
}  
* html div.outer {  
    position: relative;  
}  
*+html div.outer {  
    position: relative;  
}  
div.vertical_middle {  
    display: table-cell;
    vertical-align: middle;
    color:#FF6347;    
}  
* html div.vertical_middle {
    position: absolute;
    top: 100%;  
}  
*+html div.vertical_middle {
    position: absolute;
    top: 100%;
}  
div.vertical_middle p.inner {
    margin: 0;
    font-size:1.4em;
}  
* html div.vertical_middle p.inner {
    position: relative;
    top: -100%;
    font-size:1.4em;
}  
*+html div.vertical_middle p.inner {
    position: relative;
    top: -100%;
    font-size:1.4em;
}  
</style>
<script>
$(function(){
    $('.kids_table td').css({'border-bottom':'none'});
    $('#invitation_code_generator').button({icons:{primary:'ui-icon-circle-check'}});
    $('#invitation_code_generator').click(function(){
        $.ajax({
            url: '/mng/setinvitationcode',
            type: 'GET',
            dataType: 'json',
            data: {
            },
            beforeSend: function(xhr){
                xhr.setRequestHeader("If-Modified-Since", "Thu, 01 Jun 1970 00:00:00 GMT");
            },
            error: function(xhr, status, e){
                console.log(xhr);
                console.log(status);
                console.log(e);
                showCommonAlertDialog('エラー','システムエラーが発生しました。しばらくしてからやり直して下さい。');
            },
            success: function(d){
                console.log(d);
                if(d.status == _SEAR_){
                    showCommonAlertDialog('エラー','セッション終了です。再びログインして下さい。','/login');
                }else{
                    if(d.status == '0'){
                        $('p.inner').html(d.invitation_code);
                        $('#invitation_code_generator').hide();
                    }else{
                        showCommonAlertDialog('エラー',d.message);
                    }
                }
            },
            complete: function(){                            
            }
        });
    });
});
</script>
<h2>承認コードの確認<span>保護者又は先生が新規に登録する際に下記承認コードを入力すると承認作業が不要となります。</span></h2>
<table>
    <tr>
        <td class='kids_td'>
            <div class="outer">  
                <div class="vertical_middle">  
<?php if($this->invitation_code == ''){?>
                    <p class="inner">承認コード無</p>
<?php }else{?>
                    <p class="inner"><?php echo $this->invitation_code;?></p>
<?php }?>
                </div>
            </div>
<?php if($this->invitation_code == '' && $this->loginedInfo['member_type'] == '2'){?>
            管理者が承認コードを生成することができます。
<?php }else if($this->invitation_code == '' && $this->loginedInfo['member_type'] == '1'){?>
            <button id='invitation_code_generator'>承認コード生成</button>
<?php }?>
        </td>
    </tr>
</table>