<?php include $_SERVER['DOCUMENT_ROOT']."/include/header.php"; ?>
  <style>
    @import "/css/style_err.css";
  </style>
  <div id="wrap">
    <header>
      <h1><img src="/img/logo_slim.png"><!--KidsLink--></h1>
    </header>
    <div id="err">
      <div id="closed">
        <h1>An error occurred</h1>
        <h2><?php echo $this->message ?></h2>

        <?php if (isset($this->exception)): ?>
        
        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?>
        </pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
        </pre>

        <?php endif ?>
      </div>
    </div>
  </div>
<?php include $_SERVER['DOCUMENT_ROOT']."/include/footer.php"; ?>