<?php include $_SERVER['DOCUMENT_ROOT']."/include/header.php"; ?>
<style>
	html, body {
	  height: 100%;
	}
	div#wrap {
		width: 580px;
		top: 45%;
		margin:0px auto 20px;
		position: absolute;
		left: 50%;
    	margin-right: -50%;
    	transform: translate(-50%, -50%);
    	-moz-transform: translate(-50%, -50%);
    	-webkit-transform: translate(-50%, -50%);
	}
	input[type=text],
	input[type=password],
	input[type=email]{
		padding:5px 10px;
	}
	table#tbl_login{
		width:500px;
		margin:10px auto;
	}
	table#tbl_login th{
		color:#fff;
		text-align:right;
	}
	table#tbl_login td input[type=text],
	table#tbl_login td input[type=password],
	table#tbl_login td input[type=email],
	table#tbl_login td input[type=text]{
		width:300px;
	}
</style>
<script>
$(function(){
	$('#btn_login').button({icons:{primary:'ui-icon-locked'}});

	setCheckBoxValue('<?php echo $this->id_pw_save;?>');
});
</script>
<script src="/js/login.js"></script>
    <div id="wrap">
		<header>
			<h1><img src="/img/logo_slim.png">KidsUp</h1>
		</header>
		<div id="main">
			<div id="closed">
				<h2>ログイン</h2>
				<table id="tbl_login">
					<tr>
						<th>Eメール</th><td><input type="text" name='email' id='email' value='<?php echo $this->email;?>'></td>
					</tr>
					<tr>
						<th>パスワード</th><td><input type="password" name='pw' id='pw' value='<?php echo $this->pw;?>'></td>
					</tr>
				</table>
				<div class="btn_area">
					<input type='checkbox' name='id_pw_save' id='id_pw_save'><label for='id_pw_save'>Eメール、パスワードを保存する</label>&nbsp;&nbsp;&nbsp;<button id="btn_login">ログイン</button>
				</div>
				<div　id='lost_pw'>
					<a href='javascript:void(0);' id='issuepwform'>パスワードをお忘れの方はこちら</a>
				</div>
			</div>
		</div>
	</div>
<?php include $_SERVER['DOCUMENT_ROOT']."/include/footer.php"; ?>
