<style>
#outterDiv {
    width:930px;
    overflow-x:auto;
    overflow-y:hidden;
    text-align:left;
}
#innerDiv {
    width:160px;
    text-align:center;
    padding:10px;
    margin:2px 0px;
    display:inline-block;
    border-radius:8px;
    background-color:#FFDEAD;
    position:relative;
}
</style>
<script>
$(function(){
    $('.dailymenu_delete').click(function(){
        var date = $(this).siblings('input[type=hidden][name=date]').val();
        var filename = getFileNameFromUrl($(this).siblings('input[type=hidden][name=chg_img]').val());
        $("#yes_no_common_alert").html('給食を削除しますか？');
        $("#yes_no_common_alert").dialog({
            title:'確認',
            modal: true,
            draggable: false,
            closeOnEscape: false,
            resizable: false,
            height: 'auto',
            minHeight: 0,
            width: 'auto',
            open: function(event, ui) {
                setDialogDesign($(this));
                $('.ui-dialog-buttonpane').find('button:contains("はい")').button({icons: {primary: 'ui-icon-circle-triangle-e'}});
                $('.ui-dialog-buttonpane').find('button:contains("キャンセル")').button({icons: {primary: 'ui-icon-circle-close'}});
            },
            buttons: {
                "はい": function() {
                    $(this).dialog("close");
                    $.ajax({
                        url: '/dailymenu/delete',
                        type: 'GET',
                        dataType: 'json',
                        data: {
                            date:date,
                            filename:filename
                        },
                        beforeSend: function(xhr){
                            xhr.setRequestHeader("If-Modified-Since", "Thu, 01 Jun 1970 00:00:00 GMT");
                        },
                        error: function(xhr, status, e){
                            console.log(xhr);
                            console.log(status);
                            console.log(e);
                            showCommonAlertDialog('エラー','システムエラーが発生しました。しばらくしてからやり直して下さい。');
                        },
                        success: function(d){
                            console.log(d);
                            if(d.status == _SEAR_){
                                showCommonAlertDialog('エラー','セッション終了です。再びログインして下さい。','/login');
                            }else{
                                if(d.status == '0'){
                                    var params = {
                                        pageno:$('#pageno').val(),
                                        trigger:$('#trigger').val(),
                                        backbutton_target:true,
                                        history_seq:getNewHistorySeq()
                                    }
                                    loadAjaxPage(params, '/dailymenu/list');
                                }else{
                                    showCommonAlertDialog('エラー',d.message);
                                }
                            }
                        },
                        complete: function(){}
                    });
                },
                "キャンセル": function() {
                    $(this).dialog("close");
                }
            }
        });
    });
    $('#dailymenu_add_form').button({icons:{primary:'ui-icon-circle-plus'}});
    $('#dailymenu_add_form').click(function(){
        var params = {
            url:'/dailymenu/addform',
            action:'dailymenu',
            backbutton_target:true,
            history_seq:getNewHistorySeq()
        };
        window.History.pushState(params, null, '/');
    });
    $('#trigger').val('pageno');
    $('#pageno').val('<?php echo $this->pageno;?>');

<?php
if(count($this->olist) > 0 ){
    foreach ($this->olist as $olist) {
        $date = $olist['date'];
        foreach ($olist['ilist'] as $data) {
?>
            $('.fancybox-<?php echo $date; ?>').fancybox({
                helpers : {
                    title : {
                        type : 'inside'
                    }
                }
            });
<?php
        }
    }
}
?>
});
function goFirstPage(){
    $('#pageno').val(1);
    getDailymenuList();
}
function getListByPageno(pageno){
    $('#pageno').val(pageno);
    getDailymenuList();
}
function goNextPageGroup(){
    $('#trigger').val('nextgroup');
    getDailymenuList();
}
function goPrevPageGroup(){
    $('#trigger').val('prevgroup');
    getDailymenuList();
}
function goLastPage(){
    $('#trigger').val('lastpageno');
    getDailymenuList();
}
function getDailymenuList(){
    var params = {
        url:'/dailymenu/list',
        pageno:$('#pageno').val(),
        trigger:$('#trigger').val(),
        backbutton_target:true,
        history_seq:getNewHistorySeq()
    };
    window.History.pushState(params, null, '/');
}
</script>
<h2>給食<span></span></h2>
<?php if($this->loginedInfo['member_type'] != '3'){?>
<table id='tb_title'>
    <tr>
        <td style='text-align:left'>
            <button id='dailymenu_add_form'>作成</button>
        </td>
    </tr>
</table>
<?php }?>
<table id="tb_dailymenu">
<?php
if(count($this->olist) > 0 ){
    foreach ($this->olist as $olist) {
        $date_str = $olist['date_str'];
?>
    <tr>
        <td>
            <div style='text-align:left;background-color:#FFFACD;color:#000'><?php echo $date_str;?></div>
            <div id='outterDiv'>
<?php
        foreach ($olist['ilist'] as $data) {
?>
                    <div id='innerDiv'>
                        <input type='hidden' name='date' value='<?php echo $olist["date"]; ?>' />
                        <input type='hidden' name='chg_img' value='<?php echo $data["chg_img"]; ?>' />
                        <a class="fancybox-<?php echo $olist["date"]; ?>" data-fancybox-group="gallery" href="<?php echo $data["chg_img"]; ?>" title='<?php echo $data["br_title"];?>'><img src='<?php echo $data["thm_img"] ?>' style='width:160px;height:120px;'/></a>
<?php if($this->loginedInfo['member_type'] != '3'){?>
                        <img src='/img/icon/trash_can.png' style='position:absolute;top:95px;left:140px;cursor:pointer;' class='dailymenu_delete'/>
<?php }?>
                        <div style='width:160px;margin-left:auto;margin-right:auto;'><?php echo $data['title']; ?></div>
                    </div>
<?php
        }
?>
            </div>
        </td>
    </tr>
<?php 
    }
?>
    <tr class="page_control">
        <td colspan="6">
<?php 
    if($this->pagenator['firstPageFlag'] == 0){
?>
            <p>最初</p>
<?php 
    }else{
?>
            <a href='javascript:goFirstPage();'>最初</a>
<?php 
    }
    if($this->pagenator['preGroupFlag'] == 0){
?>
            <p>前へ</p>
<?php
    }else{
?>
            <a href='javascript:goPrevPageGroup();'>前へ</a>
<?php
    }
    foreach($this->pagenator['pagenoArr'] as $pno){
        if($pno == $this->pageno){
?>
                <p id="here"><?php echo $pno;?></p> 
<?php 
        }else{
?>
                <a href="javascript:getListByPageno(<?php echo $pno;?>)"><?php echo $pno;?></a> 
<?php
        }
    }
    if($this->pagenator['nextGroupFlag'] == 0){
?>
            <p>次へ</p>
<?php 
    }else{
?>
            <a href='javascript:goNextPageGroup();'>次へ</a>
<?php 
    }
    if($this->pagenator['lastPageFlag'] == 0){
?>
            <p>最後</p>
<?php 
    }else{
?>
            <a href='javascript:goLastPage();'>最後</a>
<?php 
    }
?>
        </td>
    </tr>
<?php
}
?>    
</table>